create table reminders (
    id bigint generated by default as identity primary key,
    message varchar(255) not null,
    phone_number varchar(255) not null,
    scheduled_at timestamp(6) not null,
    status varchar(255) not null check (status in ('PENDING', 'SENT')),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

insert into reminders (message, phone_number, scheduled_at, status, created_at, updated_at)
values (repeat('m', 255), repeat('p', 255), '2000-01-02 10:00:00', 'SENT',
        '2000-01-01 10:00:00', '2000-01-02 10:01:00');
